version: "3.8"

volumes:
  esdata: {}

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9300:9300"
      - "9200:9200"
