version: "3.8"


services:
  postgres-base:
    build:
      context: postgresql-base
    container_name: postgres-base
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'


  postgres-shard-1:
    build: postgresql-shard-1
    container_name: postgresql-shard-1
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5433:5432'
