version: "3.8"


services:
  postgresql-base:
    build:
      context: postgresql-base
    container_name: postgresql-base
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5000:5432'


  postgresql-shard-1:
    build:
      context: postgresql-shard-1
    container_name: postgresql-shard-1
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5001:5432'


  postgresql-shard-2:
    build:
      context: postgresql-shard-2
    container_name: postgresql-shard-2
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5002:5432'
