version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis-rdb:
    image: 'bitnami/redis:latest'
    volumes:
      - redis-rdb:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=no
      - REDIS_PASSWORD=str0ng_passw0rd
    ports:
      - '5000:6379'
    networks:
      - app-tier


  redis-aof:
    image: 'bitnami/redis:latest'
    volumes:
      - redis-aof:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=str0ng_passw0rd
    ports:
      - '5001:6379'
    networks:
      - app-tier


  beanstalkd:
    image: 'schickling/beanstalkd'
    ports:
      - '11300:11300'
    volumes:
      - beanstalkd:/var/lib/beanstald


volumes:
  redis-aof:
    external: true
  redis-rdb:
    external: true
  beanstalkd:
    external: true