---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/master/docker/data/logstash/config/logstash-full.yml
#
config.debug: true
http.host: 0.0.0.0
#log.level: debug
node.name: dvgerdrh1
path.config: /usr/share/logstash/pipeline